runtime: java11
instance_class: F1
env: flexible
service: processor

runtime_config:
  jdk: openjdk11

env_variables:
  SPRING_PROFILES_ACTIVE: "production"

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
